---

require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.0
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'config/initializers/devise.rb'
    - 'storage/**'
