version: '3.8'
services:
  db:
    restart: always
    image: postgres:15rc1-bullseye
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=daily_calorie_counter_development
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails_work
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file: .env.test
    environment:
      - POSTGRESQL_HOST=db
  redis:
    image: redis:7.0.5-bullseye
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
      - redis
    volumes:
      - .:/web
      - gem_cache:/usr/local/bundle/gems
    env_file: .env.test
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh
volumes:
  db_data:
  gem_cache:
