name: Rubocop

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      POSTGRESQL_PASSWORD: password
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: sudo apt-get -yqq install libpq-dev
      - run: make install
      - run: make ci-setup
      - run: make test
      - run: make lint

